title = "Andy B.Log"

[params.author]
name = "Andy Beck"
image = "img/author.jpg"
headline = "Biostatistician, runner, data storyteller"
bio = "PhD student in biostatistics at the University of Michigan working in the intersection of statistics, genomics, and population genetics. Outside interests include running, music, and improv."