project:
  type: website
  output-dir: docs

website:
  title: "Andy Beck"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Running
        menu:
          - href: race-reports/index.qmd
            text: "Running Blog"
          - href: running-pbs.qmd
            text: "Personal Bests / Progression"

format:
  html:
    respect-user-color-scheme: true
    theme: journal
    css: styles.css
    toc: true
