project:
  type: website
  output-dir: docs

website:
  title: "Andy Beck"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: journal
      dark: cyborg
    css: styles.css
    toc: true
