project:
  type: website
  output-dir: docs

website:
  title: "Andy Beck"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true
